name: Build and Publish

on:
  release:
    types: [created]  # Runs when a new release is created
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install glibc (Linux only)
        run: sudo apt-get update && sudo apt-get install -y libc6-dev
        if: runner.os == 'Linux'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Update version in setup.py
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          echo "Updating version to $VERSION in setup.py"
          sed -i "s/version=\".*\"/version=\"$VERSION\"/" setup.py
        env:
          VERSION: ${{ github.event.release.tag_name }}  # Explicitly pass release tag version

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "*-win32 *-manylinux_i686 *-manylinux1_i686"
          CIBW_ENVIRONMENT: "CXXFLAGS=-std=c++17"

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ github.run_id }}-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  publish:
    name: Publish to PyPI
    needs: build_wheels  # Waits for the build_wheels job to complete
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Download built wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-${{ github.run_id }}-${{ matrix.os }}
          path: dist

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: "${{ secrets.PYPI_API_TOKEN }}"
        run: twine upload dist/* --repository-url https://upload.pypi.org/legacy/
